compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.8.1.cjs

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  zarclays:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAlwaysAuth: true